### ISSUE TITLE
The certificate that is attached to your distribution doesn't cover the alternate domain name (CNAME)

### ISSUE THREAD

**Issue by oliwerhelsen** [aws-samples/aws-saas-factory-eks-reference-architecture#58]
Hi guys,

I'm trying to deploy the VNext branch with the --domain flag and getting the following error:
- "Invalid request provided: The certificate that is attached to your distribution doesn't cover the alternate domain name (CNAME) that you're trying to add."

Any idea on what goes wrong here? It says something about permission. I'm deploying to eu-north-1.

Best regards
Oliwer H.

**Comment by ranjith-aws** [comment]
Hi @oliwerhelsen We are checking this and will report back what we find. @zpbappi-aws

**Comment by zpbappi-aws** [comment]
@oliwerhelsen thank you for reporting this. Can I please ask you to provide the CloudFormation event logs? We need this to understand at which step did it fail doing exactly what. Make sure to include the first failure in your CloudFormation Stack events. The first failure generally indicates the root cause of cascading failures.
