### ISSUE TITLE
Error during tenant registration - no record for api.yourdomain in route53 

### ISSUE THREAD

**Issue by lal-verma** [aws-samples/aws-saas-factory-eks-reference-architecture#61]
Getting an error while doing tenant registration. The browser side error snapshot is below. While digging more, found that no record in route53 is found mapped to api.yourdomain getting referred at tenant registration. 

************************************************************

<img width="1074" alt="Screen Shot 2022-09-15 at 4 05 00 PM" src="https://user-images.githubusercontent.com/32193810/190514535-5fef5552-1fe6-4596-b0a8-1bd47ace72c9.png">

**Comment by lal-verma** [comment]
As discussed with @tobuck-aws , this seems to be helm issue discussed [here](https://github.com/helm/helm/issues/10975.)

The workaround is to update the helm version

`curl -L https://git.io/get_helm.sh | bash -s -- --version v3.8.2`

**Comment by tobuck-aws** [comment]
Well, more specifically, the issue was that the install of the `external-dns` controller failed because helm threw an invalid api version issue. Pinning the version to 3.8.2 allowed external dns to be installed, after which it correctly synced the Route 53 records. Note that if you install external-dns after that failure, you'll have to delete and re-create the tenant-registration (basically the whole deployment-master.yaml) stack so the changes get picked up.
