### ISSUE TITLE
Unable to install: SaaSApi Cloudformation Stack failing 

### ISSUE THREAD

**Issue by lal-verma** [aws-samples/aws-saas-factory-eks-reference-architecture#64]
Tried to run the eks reference solution, on vNext branch, in a new account, new region.  Cloudformation stack SaaSApi is failing.

Command Used

`npm run deploy --email=iamlal@amazon.com`

Error Screenshot

<img width="1258" alt="Screen Shot 2022-09-28 at 9 50 48 AM" src="https://user-images.githubusercontent.com/32193810/192812698-c3416819-e864-4da4-810f-509babc51eb1.png">

**Comment by thecount1986** [comment]
Hi, any progress on this one? I'm getting the same thing.

**Comment by james-ahearn** [comment]
I too am facing the above issue

**Comment by ranjith-aws** [comment]
This looks like some kind of a timing/race condition issue with the NLB not being ready and because of that the SaaSApi stack times out. I tried a few times and I ran in to this once. The workaround for now is:

Go to Cloud9 and run the same npm run deploy command that you used previously to create the stack. Important to make sure you use the same command that you ran previously with the same parameters, it could be either the 1/ with domain or 2/ without the domain option.

Please try that and let me know how it goes. Meanwhile we will work on providing a clean alternative to this issue

**Comment by thecount1986** [comment]
Thanks, @ranjith-aws, I did something similar. I went to CloudFront and copied the template and create a new stack using the same template and ran it again and it worked.
