### ISSUE TITLE
Error while provisioning new tenant(vnext) - From Landing Static site 

### ISSUE THREAD

**Issue by thecount1986** [aws-samples/aws-saas-factory-eks-reference-architecture#68]
<img width="1786" alt="Screen Shot 2022-11-12 at 6 43 53 PM" src="https://user-images.githubusercontent.com/13307605/201500285-c75a999f-5ff5-4e9e-9d6d-f60c295287d0.png">

**Comment by zpbappi-aws** [comment]
Hi @thecount1986, in your AWS console, if you look at the permissions for the CodeBuild project name `TenantOnboardingProject`, it should have the necessary `cloudfront:AssociateAlias` for the proper CloudFront distribution. Can you please confirm if that is the case for you? 

If the above setup is correct, then in `/services/tenant-onboarding/lib/tenant-onboarding-stack.ts` line# 113 tells the custom resource to infer the permission from SDK calls. Try changing it to IAM policy instead as below:
```
policy: cr.AwsCustomResourcePolicy.fromStatements([
                new iam.PolicyStatement({
                    actions: ["cloudfront:AssociateAlias"],
                    effect: iam.Effect.ALLOW,
                    resources: [distributionArn]
                })
            ])
```
Let me know if the above setup works for you.

**Comment by thecount1986** [comment]
I cloned the repo for TenantOnboarding from CodeCommit and upload this change you suggested. Still having the same error once I trigger a new tenant onboarding.

**Comment by zpbappi-aws** [comment]
Hi @thecount1986, thanks for the report. This is unexpected behavior. I will need further detail. I will try a custom domain based deployment soon and try to find out what's happening. I will update here accordingly.

**Comment by thecount1986** [comment]
Hi @thecount1986 few things we have noticed happening in the code after looking into it. 
 1. Configuration parameters are coming empty. So we add default parameters to see if we could get around it and continue the deployment of all the services. 
 2. we added 
         policy: cr.AwsCustomResourcePolicy.fromStatements([
                    new iam.PolicyStatement({
                        **actions: ["cloudfront:AssociateAlias", "cloudfront:UpdateDistribution"],**
                        effect: iam.Effect.ALLOW,
                        resources: [distributionArn],
                    })
                ])
     We are now stuck in the error in the picture below. 

<img width="1133" alt="Screen Shot 2022-11-17 at 9 51 56 AM" src="https://user-images.githubusercontent.com/13307605/202495633-50573c5b-fbf3-452d-a381-27dc26eb726e.png">

**Comment by zpbappi-aws** [comment]
Hi @thecount1986, thank you for figuring out the problem. It does need UpdateDistribution permission to associate an alias. Would you mind creating a small PR to add that so that we can acknowledge you contribution and merge it in?

Regarding the configuration parameters, can you please elaborate a little where your are expecting the parameter values in the code, how you are initiating the deployment, and what is coming as empty?

**Comment by thecount1986** [comment]
I have started the deployment of the stack with all the parameters I get to the point where the landing, admin and API are deployed. The issue is when I try to deploy a tenant. In the T/services/tenant-onboarding/lib/tenant-onboarding-stack.ts and I was able to find 3 problems that we were able to fix and I will include in the PR 
   1.  if (usingCustomDomain) {
            // add alias to existing distribution
            const tenantAppDomain = **`${tenantId.valueAsString}**.${props.customDomain}`;

   2. policy: cr.AwsCustomResourcePolicy.fromStatements([
        new iam.PolicyStatement({
        actions: ["cloudfront:AssociateAlias", **"cloudfront:UpdateDistribution"]**,
        effect: iam.Effect.ALLOW,
        resources: [distributionArn],
        })
        ])
   3. const distributionArn = Arn.format({
                service: "cloudfront",
                resource: "distribution",
                **region: "",**.  // this is needed 
                resourceName: appDistributionId.valueAsString,
            }, this);

I was wrong in adding default or hard-coded values. The current error is still related to "invalid Alias DNS Txt Record". Do you have end result template expected to see if I can walk backward from there to the code?

**Comment by ranjith-aws** [comment]
HI @thecount1986 Apologies for the delayed response on this. I have made code updates here, so please feel free to try it out when you have a chance. I don't think the section where we associate the alias to Cloudfront is required because we already have *.app.YOUR_DOMAIN.com as the alternate domain name. Now,if you need more control over the aliases that are being associated, then you probably need that, but otherwise not required.
Hope that helps. Also, we have made updates to the ReadMe and the steps to get this setup. Please check when you have a chance and let us know if any thoughts/feedbacks.
