### ISSUE TITLE
Error while onboarding a new tenant (vnext)

### ISSUE THREAD

**Issue by aortizllorens** [aws-samples/aws-saas-factory-eks-reference-architecture#76]
Hi, I'm getting the following error while trying to onboard a new tenant from the admin site.

`TenantStack-**** |  8/20 | 11:17:33 AM | CREATE_FAILED        | AWS::Lambda::Function                 | AWS679f53fac002430cb0da5b7982bd2287 (AWS679f53fac002430cb0da5b7982bd22872D164C4C) Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: b2602455-58ef-49e8-9ccf-ae1a8c5e1014)" (RequestToken: 01fc70e2-1fba-3484-43a7-41799b035ce9, HandlerErrorCode: InvalidRequest)`

I tried to upgrade the aws-cdk library (to version 2.90.0) but that resulted on a different error:

`RangeError: The name of a ServiceAccount object must be a valid DNS subdomain name.`

Is there any way to mitigate this?

Thanks in advance!

**Comment by SimiShaju** [comment]
Hi 

I am also facing the same error . Did you find any solution for this issue 

Thanks!

**Comment by ranjith-aws** [comment]
I am checking this issue and will report back my findings. Looks like the nodeJs version here needs an update, but will check and get back

**Comment by SimiShaju** [comment]
Hi 

As mentioned by @aortizllorens after upgrading the cdk version , I am facing error "RangeError: The name of a ServiceAccount object must be a valid DNS subdomain name".

Please let me know how to fix this issue

Thanks in advance!

**Comment by SimiShaju** [comment]
Hi @ranjith-aws

We were able to mitigate the issue 

**Problem** :
While onboarding a new tenant from admin site the following error was observed

`Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: b2602455-58ef-49e8-9ccf-ae1a8c5e1014)" (RequestToken: 01fc70e2-1fba-3484-43a7-41799b035ce9, HandlerErrorCode: InvalidRequest)`

 After upgrading the aws-cdk-lib version to 1.80.0 we were able to resolve the nodejs version issue. However the tenant onboarding stack was failing with  
`"RangeError:The name of a ServiceAccount object must be a valid DNS subdomain name".`

**RCA**:
On analysis we found that the cfn parameter **tenantId** mentioned in file **tenant-onboarding/lib/tenant-onboarding-stack.ts** was not passing the intended value during build (wherever the value is reffered as "tenantId.valueAsString"). Since the values were not read properly namespace creation as well as serviceaccount creation the  tenantid value was being passed as empty , hence causing the above error

**Solution:**
Inorder to mitigate this issue code changes were made to read  tenantid  from environment variables.
The changes made are shown below

File name : tenant-onboarding/bin/tenant-onboarding.ts

> new TenantOnboardingStack(app, 'TenantStack-${process.env.TENANT_ID}', {
>   env,
>   plan: process.env.PLAN!, 
>   tenantid: process.env.TENANT_ID!,
>   customDomain: appCustomDomain,
>   hostedZoneId: appHostedZoneId,
> });

File name : tenant-onboarding/lib/tenant-onboarding-stack.ts
> export interface TenantOnboardingStackProps extends StackProps {
>     readonly plan: string
>     readonly tenantid: string
>     readonly customDomain?: string
>     readonly hostedZoneId?: string
> }

And wherever the tenantId value is reffered as props.tenantid instead of tenantId.valueAsString
Sample code is given below : 

> 
> //Create Tenant namespace
> const ns = cluster.addManifest('tenant-namespace', {
> 	"apiVersion": "v1",
> 	"kind": "Namespace",
> 	"metadata": {
> 		"name": props.tenantid,
> 		"labels": {
> 			"name": props.tenantid,
> 			"saas/tenant": "true"
> 		}
> 	}
> });
> 
> // create service account for tenant
> const tenantServiceAccount = cluster.addServiceAccount('TenantServiceAccount', {
> 	name: '${props.tenantid}-service-account',
> 	namespace: props.tenantid
> });

After making these changes we were able to onboard a new tenant successfully and tenant services also got deployed 

Note : Back quotes were replaced in the code as single quotes as the comment was not displaying properly

ThanksI

**Comment by ranjith-aws** [comment]
@SimiShaju This is great! Thanks for reporting back. Since you have the fix/changes needed here, do you mind creating a PR for this? I can then test it on my side and merge the changes, if everything looks good.

**Comment by SimiShaju** [comment]
@ranjith-aws 

Sure I will raise a PR and will submit the changes to you.

Thanks 
Simi Shaju

**Comment by ranjith-aws** [comment]
Changes pushed. Closing issue
